baseURL = '/hugobase/'
languageCode = 'en-gb'
title = 'Hugo Test Site'
disableKinds = ["taxonomy"]

[module]
[[module.mounts]]
    source = "./node_modules/jquery/dist"
    target = "static/assets/jquery"
[[module.mounts]]
    source = "./node_modules/bootstrap/dist/js"
    target = "static/assets/bootstrap"
[[module.mounts]]
    source = "./assets/css/"
    target = "static/assets/css"
[[module.mounts]]
    source = "./assets/images/"
    target = "static/assets/images"


 [params]
 logoImgURL = "assets/images/logo.png"
 [params.styles]
 headFootBG = "bg-purple"
 headBorderColor = "border-green"
 [params.copyright]
 year = "2025"
 name = "Whizzsfe Web Services"